# Generated by Django 5.2.6 on 2026-07-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_id', models.CharField(max_length=20, unique=True, verbose_name='Resident ID')),
                ('full_name', models.CharField(max_length=150)),
                ('room_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('discharged', 'Discharged'), ('pending', 'Pending')], default='active', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('payer_source', models.CharField(max_length=50)),
                ('admission_date', models.DateField()),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
