# Generated by Django 5.2.6 on 2026-07-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_planning', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarePlan',
        ),
    ]
