# Generated by Django 5.2.6 on 2026-07-13 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('assessment_type', models.CharField(choices=[('initial', 'Initial'), ('reassessment', 'Reassessment')], default='initial', max_length=20)),
                ('assessment_date', models.DateField(auto_now_add=True)),
                ('total_adl_score', models.IntegerField(default=0)),
                ('loc_tier', models.CharField(blank=True, max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='residents.resident')),
            ],
            options={
                'ordering': ['-assessment_date', '-version'],
            },
        ),
    ]
