# Generated by Django 5.2.6 on 2026-07-21 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_assessment_assessment_type_assessment_is_locked_and_more'),
        ('residents', '0010_resident_payer_source_resident_resident_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_id', models.AutoField(db_column='HolidayID', primary_key=True, serialize=False)),
                ('holiday_date', models.DateField(db_column='HolidayDate', unique=True)),
                ('holiday_name', models.CharField(db_column='HolidayName', max_length=250)),
                ('is_national_holiday', models.BooleanField(db_column='IsNationalHoliday', default=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'Holidays',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
        migrations.AlterModelOptions(
            name='assessmentdetail',
            options={'verbose_name': 'Assessment Detail', 'verbose_name_plural': 'Assessment Details'},
        ),
        migrations.AlterModelOptions(
            name='carelevel',
            options={'ordering': ['sort_order'], 'verbose_name': 'Care Level', 'verbose_name_plural': 'Care Levels'},
        ),
        migrations.AddField(
            model_name='assessment',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assessment Date'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='care_level',
            field=models.CharField(blank=True, choices=[('independent', 'Independent'), ('minimal_assist', 'Minimal Assist'), ('moderate_assist', 'Moderate Assist'), ('maximum_assist', 'Maximum Assist'), ('total_care', 'Total Care')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='clinical_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assessment',
            name='cognitive_status',
            field=models.CharField(blank=True, choices=[('alert_oriented', 'Alert & Oriented'), ('alert_oriented_x1', 'Alert & Oriented x1'), ('alert_oriented_x2', 'Alert & Oriented x2'), ('alert_oriented_x3', 'Alert & Oriented x3'), ('confused', 'Confused'), ('lethargic', 'Lethargic'), ('obtunded', 'Obtunded'), ('stupor', 'Stupor'), ('coma', 'Coma')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_adl_score',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_iadl_score',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='total_adl_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='total_iadl_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentdetail',
            name='category',
            field=models.CharField(blank=True, choices=[('adl', 'Activities of Daily Living'), ('iadl', 'Instrumental ADL'), ('vital_sign', 'Vital Sign')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assessmentdetail',
            name='item_key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='assessmentdetail',
            name='item_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assessmentdetail',
            name='max_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentdetail',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assessmentdetail',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='caregoal',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caregoal',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caregoal',
            name='measure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caregoal',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carelevel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='carelevel',
            name='max_adl_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carelevel',
            name='min_adl_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carelevel',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='adl_total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessed_by',
            field=models.ForeignKey(blank=True, db_column='assessed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_performed', to=settings.AUTH_USER_MODEL, verbose_name='Assessed By'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('initial', 'Initial Assessment'), ('periodic', 'Periodic Assessment'), ('quarterly', 'Quarterly Assessment'), ('annual', 'Annual Assessment'), ('change_of_condition', 'Change of Condition')], default='initial', max_length=30),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='confirmed_care_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medical.carelevel'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='residents.resident', verbose_name='Resident'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='suggested_care_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medical.carelevel'),
        ),
        migrations.AlterField(
            model_name='assessmentdetail',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='medical.assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentdetail',
            name='metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medical.assessmentmetric'),
        ),
        migrations.AlterField(
            model_name='assessmentdetail',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assessmentdetail',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caregoal',
            name='care_plan',
            field=models.ForeignKey(db_column='care_plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='medical.careplan'),
        ),
        migrations.AlterField(
            model_name='caregoal',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('ACHIEVED', 'Achieved'), ('NOT_MET', 'Not Met')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_care_plans', to='residents.resident'),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('DISCONTINUED', 'Discontinued')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='AssessmentDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_name', models.CharField(max_length=255)),
                ('diagnosis_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='medical.assessment')),
            ],
            options={
                'verbose_name': 'Assessment Diagnosis',
                'verbose_name_plural': 'Assessment Diagnoses',
                'db_table': 'assessment_diagnoses',
                'ordering': ['-is_primary', 'diagnosis_name'],
            },
        ),
    ]
