# Generated by Django 5.2.6 on 2026-07-21 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_holiday_alter_assessment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_medical_care_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='careplan',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_medical_care_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='careplan',
            name='last_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('ACTIVE', 'Active'), ('REVIEW_DUE', 'Review Due'), ('NEEDS_UPDATE', 'Needs Update'), ('RESOLVED', 'Resolved'), ('DISCONTINUED', 'Discontinued')], default='DRAFT', max_length=20),
        ),
    ]
