# Generated by Django 5.2.6 on 2026-07-21 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_npi'),
        ('medical', '0008_holiday_alter_assessment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplan',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_care_plans', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='careplan',
            name='last_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('review_due', 'Review Due'), ('needs_update', 'Needs Update'), ('resolved', 'Resolved'), ('discontinued', 'Discontinued')], default='draft', max_length=20),
        ),
    ]
