# Generated by Django 5.2.6 on 2026-07-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_careplan_assigned_to_careplan_last_review_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={},
        ),
    ]
