# Generated by Django 5.2.6 on 2026-07-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_careplan_approved_at_careplan_approved_by_and_more'),
        ('medical', '0010_alter_holiday_options'),
    ]

    operations = [
    ]
