# Generated by Django 5.2.6 on 2026-07-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=140.0, max_digits=18),
        ),
    ]
